# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [master]

jobs:
  maven-build-docker:
    # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    -
      name: Get short SHA
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
    -
      name: Store short SHA as environment variable
      run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    -
      name: Set env
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    -
      name: Test tag name
      run: |
        echo $TAG_NAME
        echo ${{ env.TAG_NAME }}
    -
      name: Checkout repository
      uses: actions/checkout@v2
    -
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    -
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    -
      name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true -Dseb-sps-version="${{ env.TAG_NAME }}-${{ env.SHA }}" 
      env: 
         seb-sps-version: ${{ env.TAG_NAME }}-${{ env.SHA }}
    -
      name: Simplify package name
      run: mv target/seb-screen-proctoring-service-${{ env.TAG_NAME }}-${{ env.SHA }}.jar target/seb-sps.jar
    -
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: target/seb-sps.jar

  docker-build:
    needs: maven-build-docker
    # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    -
      name: Set env
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    -
      name: Test
      run: |
        echo $TAG_NAME
        echo ${{ env.TAG_NAME }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Checkout repository
      uses: actions/checkout@v2
    -
      name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
          name: Package
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          anhefti/seb-sps:${{ env.TAG_NAME }}
          
  cleanup:
     # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    -
      name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
          name: Package